### ISSUE TITLE
app跑不通 没找到clip_api函数

### ISSUE THREAD

**Issue by Tany-g** [sugarandgugu/Text2Image-Retrieval#1]
` /home/ubuntu/anaconda3/envs/clip/lib/python3.10/site-packages/gradio_client/documentation.py:103: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
/home/ubuntu/anaconda3/envs/clip/lib/python3.10/site-packages/gradio_client/documentation.py:103: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
/home/ubuntu/GITHUG/Text2Image-Retrieval/text2image.py:33: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  out = gr.Gallery(label="检索结果为：").style(grid=4, height=200)
/home/ubuntu/GITHUG/Text2Image-Retrieval/text2image.py:33: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'grid_cols' in the constructor instead.
  out = gr.Gallery(label="检索结果为：").style(grid=4, height=200)
Traceback (most recent call last):
  File "/home/ubuntu/GITHUG/Text2Image-Retrieval/app.py", line 7, in <module>
    [text2image_gr()],
  File "/home/ubuntu/GITHUG/Text2Image-Retrieval/text2image.py", line 35, in text2image_gr
    btn.click(fn=clip_api, inputs=inputs, outputs=out)
NameError: name 'clip_api' is not defined. Did you mean: 'clip_base'?`

**Comment by wujack123** [comment]
请问解决了吗

**Comment by Tany-g** [comment]
没解决，我用faiss 自己实现了一下
